export const ORDER_TYPES = {
  DELIVERY: 'DELIVERY',
  PICKUP: 'PICKUP'
};

export const HOME_TYPES = {
  HOUSE: 'HOUSE',
  APARTMENT: 'APARTMENT'
};

export const STEPS = {
  ADDRESS_FORM: 0,
  PICK_NUMBER_OF_PIZZAS: 1,
  CONFIRMATION: 2
};

