export const ORDER_TYPES = {
  DELIVERY: 'DELIVERY',
  PICKUP: 'PICKUP'
};

export const HOME_TYPES = {
  HOUSE: 'HOUSE',
  APARTMENT: 'APARTMENT'
};

export const STEPS = {
  CONTACT_FORM: 0,
  PIZZA_BUILDER: 1,
  CONFIRMATION: 2,
  THANK: 3
};

export const ORDER_STATUS = {
  EMITTED: 'EMITTED',
  IN_PREPARATION: 'IN_PREPARATION',
  COOKING: 'COOKING',
  ON_DELIVERY: 'ON_DELIVERY',
  READY: 'READY',
};

