export const INGREDIENTS = {
  PEPERRONI: 'PEPERRONI',
  HAM: 'HAM',
  VEGETABLES: 'VEGETABLES',
  CORN: 'CORN'
};

export const INGREDIENTS_PROPORTIONS = {
  LEFT: 'LEFT',
  WHOLE: 'WHOLE',
  RIGHT: 'RIGHT'
};
